"""
Lesson View Component

Renders lesson content and questions.
"""

import streamlit as st


def render_lesson_view(topic):
    """
    Render the lesson view for a topic.
    
    Args:
        topic: Topic object with name, level, difficulty, content, prerequisites
    """
    # Display lesson content
    if hasattr(topic, 'content') and topic.content:
        st.markdown(topic.content)
    else:
        st.info("No lesson content available for this topic.")
    
    # Show prerequisites if any
    if hasattr(topic, 'prerequisites') and topic.prerequisites:
        with st.expander("📚 Prerequisites"):
            st.markdown("Before this topic, you should know:")
            for prereq in topic.prerequisites:
                st.markdown(f"- {prereq}")


def render_lesson_content_llm(lesson_content):
    """
    Render LLM-generated lesson content.
    
    Args:
        lesson_content: String content generated by LLM
    """
    st.markdown(lesson_content)
